require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'
require 'lib/yarg'

desc 'Default: run unit tests.'
task :default => :test

desc 'Test the yarg gem.'
Rake::TestTask.new do |t|
  t.libs << 'lib' << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate documentation for the yarg gem.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Yarg'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.markdown')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

spec = Gem::Specification.new do |s|
  s.name              = "yarg"
  s.version           = Yarg::VERSION
  s.summary           = "Yet Another Ruby Generator"
  s.homepage          = "http://github.com/rmm5t/yarg"
#   s.rubyforge_project = "yarg"

  s.files       = FileList["[A-Z]*", "{bin,lib,test}/**/*"]
  s.executables = s.files.grep(/^bin/) { |f| File.basename(f) }

  s.has_rdoc         = true
  s.extra_rdoc_files = ["README.markdown"]
  s.rdoc_options     = ["--line-numbers", "--inline-source", "--main", "README.markdown"]

  s.authors = ["Ryan McGeary"]
end

Rake::GemPackageTask.new spec do |pkg|
  pkg.need_tar = true
  pkg.need_zip = true
end

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc, :clobber_package]

desc "Generate a gemspec file for GitHub"
task :gemspec do
  File.open("#{spec.name}.gemspec", 'w') do |f|
    f.write spec.to_ruby
  end
end
